Fix validation of server42 ingress rules
telstra/open-kilda pull request #3711
Opened 2020-09-04 15:39 UTC by rozdy

Close #3673

2020-09-05 06:24 UTC, surabujin commented on src-java/kilda-model/src/main/java/org/openkilda/converters/CookieConverter.java
> -package org.openkilda.persistence.converters;
Why it is moved outside neo/ogm module?

2020-09-05 06:24 UTC, surabujin commented on src-java/kilda-model/src/main/java/org/openkilda/model/FlowPath.java
> +    @Convert(CookieConverter.class)
What the difference?

2020-09-07 07:11 UTC, timofei-durakov requested changes
No unit tests, please add at least one reproducing this issue

2020-09-07 10:19 UTC, rozdy commented
> No unit tests, please add at least one reproducing this issue

Reworked and added test.

2020-09-09 07:55 UTC, timofei-durakov approved these changes

2020-09-09 08:02 UTC, niksv approved these changes

2020-09-09 10:18 UTC, sergii-iakovenko approved these changes

2020-09-09 10:18 UTC, merged