ignore test according to #3847
telstra/open-kilda pull request #3848
Opened 2020-11-11 14:18 UTC by andriidovhan

2020-11-11 16:59 UTC, rtretyak approved these changes

2020-11-11 16:59 UTC, rtretyak commented on src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortAntiflapSpec.groovy
> +import org.junit.Ignore
should be spock.lang.Ignore

2020-11-11 17:00 UTC, rtretyak requested changes
^

2020-11-11 17:21 UTC, andriidovhan commented on src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortAntiflapSpec.groovy
> +import org.junit.Ignore
fixed

2020-11-12 14:27 UTC, rtretyak approved these changes

2020-11-13 14:58 UTC, merged