Added kafka message versioning with ZooKeeper
telstra/open-kilda pull request #3872
Opened 2020-11-23 21:13 UTC by niksv

2020-12-03 17:16 UTC, nikitamarchenko requested changes

2020-12-04 07:39 UTC, niksv commented on src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/kafka/versioning/VersioningConsumerInterceptor.java
> +        log.info("Initializing VersioningConsumerInterceptor");
fixed

2020-12-04 07:39 UTC, niksv commented on src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/kafka/versioning/VersioningProducerInterceptor.java
> +        log.info("Initializing VersioningProducerInterceptor");
fixed

2020-12-04 07:40 UTC, niksv commented on src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/kafka/versioning/VersioningProducerInterceptor.java
> +            e.printStackTrace();
fixed

2020-12-04 07:41 UTC, niksv commented on src-java/blue-green/src/main/java/org/openkilda/bluegreen/ZkClient.java
> +        ensureZNode("".getBytes(), path);
fixed

2020-12-04 07:51 UTC, niksv commented on src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/kafka/versioning/VersioningProducerInterceptor.java
> +        record.headers().add(MESSAGE_VERSION_HEADER, version.getBytes());
fixed

2020-12-04 08:06 UTC, niksv commented on src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/kafka/versioning/VersioningConsumerInterceptor.java
> +        // nothing to do here
fixed

2020-12-04 09:53 UTC, niksv commented on src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/kafka/versioning/VersioningConsumerInterceptor.java
> +            log.error("Component {} with id {} can't connect to ZooKeeper with connection string: {}, received: {}",
fixed

2020-12-04 09:53 UTC, niksv commented on src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/kafka/versioning/VersioningProducerInterceptor.java
> +            log.error("Component {} with id {} can't connect to ZooKeeper with connection string: {}, received: {}",
fixed

2020-12-04 12:10 UTC, niksv commented on src-java/base-topology/base-storm-topology/src/test/resources/topology.properties
> +zookeeper.hosts=localhost:2181/kilda
fixed

2020-12-08 10:50 UTC, nikitamarchenko requested changes

2020-12-08 10:50 UTC, nikitamarchenko commented on src-java/server42/server42-stats/src/main/java/org/openkilda/server42/stats/kafka/KafkaConfig.java
> +    public ConsumerFactory<?, ?> kafkaConsumerFactory(KafkaProperties properties) {
move it config files

2020-12-08 10:50 UTC, nikitamarchenko commented on src-java/server42/server42-stats/src/main/java/org/openkilda/server42/stats/kafka/KafkaConfig.java
> +    public ProducerFactory<?, ?> kafkaProducerFactory(KafkaProperties properties) {
move it config files

2020-12-08 10:50 UTC, nikitamarchenko commented on src-java/server42/server42-control/src/main/java/org/openkilda/server42/control/kafka/KafkaConfig.java
> +    public ConsumerFactory<?, ?> kafkaConsumerFactory(KafkaProperties properties) {
move it config files

2020-12-08 10:50 UTC, nikitamarchenko commented on src-java/server42/server42-control/src/main/java/org/openkilda/server42/control/kafka/KafkaConfig.java
> +    public ProducerFactory<?, ?> kafkaProducerFactory(KafkaProperties properties) {
move it config files

2020-12-08 11:52 UTC, niksv commented on src-java/server42/server42-stats/src/main/java/org/openkilda/server42/stats/kafka/KafkaConfig.java
> +    public ConsumerFactory<?, ?> kafkaConsumerFactory(KafkaProperties properties) {
fixed

2020-12-08 11:53 UTC, niksv commented on src-java/server42/server42-control/src/main/java/org/openkilda/server42/control/kafka/KafkaConfig.java
> +    public ConsumerFactory<?, ?> kafkaConsumerFactory(KafkaProperties properties) {
fixed

2020-12-08 11:53 UTC, niksv commented on src-java/server42/server42-stats/src/main/java/org/openkilda/server42/stats/kafka/KafkaConfig.java
> +    public ProducerFactory<?, ?> kafkaProducerFactory(KafkaProperties properties) {
fixed

2020-12-08 11:53 UTC, niksv commented on src-java/server42/server42-control/src/main/java/org/openkilda/server42/control/kafka/KafkaConfig.java
> +    public ProducerFactory<?, ?> kafkaProducerFactory(KafkaProperties properties) {
fixed

2020-12-08 12:10 UTC, nikitamarchenko approved these changes

2020-12-09 07:32 UTC, dpoltavets approved these changes

2020-12-25 12:34 UTC, merged