update tests according to flowHistoryStatuses
telstra/open-kilda pull request #4080
Opened 2021-02-19 13:49 UTC by andriidovhan

2021-03-02 10:39 UTC, rtretyak requested changes

2021-03-02 10:39 UTC, rtretyak commented on src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowHistoryV2Spec.groovy
> +        and: "Flow history statuses returns all flow statuses during for the whole life cycle"
```suggestion
        and: "Flow history statuses returns all flow statuses for the whole life cycle"
```

2021-03-02 10:39 UTC, rtretyak commented on src-java/testing/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceV2Impl.java
> +    public List<FlowHistoryStatusesResponse> getFlowHistoryStatuses(String flowId, Long timeFrom, Long timeTo,
Why List?

2021-03-02 11:56 UTC, andriidovhan commented on src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowHistoryV2Spec.groovy
> +        and: "Flow history statuses returns all flow statuses during for the whole life cycle"
fixed

2021-03-02 11:56 UTC, andriidovhan commented on src-java/testing/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceV2Impl.java
> +    public List<FlowHistoryStatusesResponse> getFlowHistoryStatuses(String flowId, Long timeFrom, Long timeTo,
my bad, fixed

2021-03-16 09:58 UTC, rtretyak approved these changes

2021-03-24 09:12 UTC, merged