Rule Manager Floodlight integration
telstra/open-kilda pull request #4627
Opened 2021-12-20 08:35 UTC by timofei-durakov

2021-12-20 12:44 UTC, rozdy commented on src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/converter/rulemanager/OfFlowModConverter.java
> +    public OFGroupAdd convertInstallGroupCommand(GroupSpeakerData commandData, OFFactory ofFactory) {
Move group related methods to separate converter or rename current one

2021-12-20 12:44 UTC, rozdy commented on src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/converter/rulemanager/OfFlowModConverter.java
> +        List<OFAction> ofActions = OfInstructionsConverter.INSTANCE.convertApplyActions(bucket.getWriteActions(),
Rename `convertApplyActions` -> `convertActions`. This method may be used for applyActions and writeActions.

2021-12-20 12:44 UTC, rozdy commented on src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/converter/rulemanager/OfFlowModConverter.java
> +                throw new IllegalArgumentException("Unknown watch port");
Add details to error message. `String.format("Unknown watch port %s", watchPort)`

2021-12-20 12:44 UTC, rozdy commented on src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/converter/rulemanager/OfFlowModConverter.java
> +    private OFPort fromOfPort(OFPort watchPort) {
Probably method result type should be WatchPort

2021-12-20 12:44 UTC, rozdy commented on src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/converter/rulemanager/OfFlowModConverter.java
> +            throw new IllegalArgumentException("Unknown watch group");
Add details to all error messages in this converter

2021-12-20 12:44 UTC, rozdy commented on src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/converter/rulemanager/OfMatchConverter.java
> +        }
IN_PORT match is missing here

2021-12-21 11:14 UTC, dpoltavets approved these changes

2021-12-21 12:27 UTC, dpoltavets commented on src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/rulemanager/OfSpeakerService.java
> +            data.buildInstall(holder, switchId);
buildDelete

2021-12-22 14:19 UTC, rozdy approved these changes

2021-12-22 17:06 UTC, surabujin requested changes
The strongest objection from me is incorrect "recussive" in flows installation stages. It must be correct, or must be crystall clean described in extremmely notable place how "special" it implemented with all limitation. (Correct implementation ~10-15 LOC is much simplier that such description).

And the second objection - analyse of OF match object, it definetly must be reworked.

2021-12-22 17:50 UTC, surabujin approved these changes

2021-12-23 08:12 UTC, merged