Enforce switch multi-table flag in RuleManager if there's existing multi-table flow
telstra/open-kilda pull request #4686
Opened 2022-01-31 07:46 UTC by sergii-iakovenko

2022-01-31 07:55 UTC, niksv requested changes
It is totally OK to have switchProps multitable = false and flow.srcWithMultiTable = true.

Use case - when you try to disable multiTable on swich you
1. set swProps.multiTable = false
2. at this moment you have flows with srcMultitable = true and swProps.multiTable=false
3. sync all flows
4. at this moment you have flows with srcMultitable = false and swProps.multiTable=false

2022-02-01 07:19 UTC, sergii-iakovenko commented
@niksv Please, review the new changes (with keepMultitableForFlow flag).

2022-02-01 10:11 UTC, dpoltavets approved these changes

2022-02-01 13:56 UTC, niksv approved these changes

2022-02-02 08:38 UTC, timofei-durakov approved these changes

2022-02-03 21:15 UTC, merged