Add validation for LAG port update request
telstra/open-kilda pull request #4776
Opened 2022-04-18 18:40 UTC by vshakirova

Close #4719

2022-05-03 10:22 UTC, surabujin requested changes
One area related to port speed is missing/not changed - ISL speed. We need to have at least note/todo record about changing ISL speed on OTHER_UPDATE event. Mentioned chage for ISL speed can become to complex/big for current PR.

2022-05-04 06:42 UTC, vshakirova commented on docker/db-migration/migrations/020-add-port-class.yaml
> +  - changeSet:
Yep, now we have relation between port and switch obj. But it is described in FermaPortRepo. Not sure about related class, what do you mean?

2022-05-04 06:43 UTC, vshakirova commented on docs/design/network-discovery/switch-FSM.puml
> +SETUP : enter / save NEW port in BD
yes, sorry. my mistake. I'll fix this issue.

2022-05-04 12:46 UTC, vshakirova commented on docker/db-migration/migrations/020-add-port-class.yaml
> +        - sql: "CREATE INDEX port.switch_id IF NOT EXISTS NOTUNIQUE_HASH_INDEX"
I will do that. thank you

2022-05-05 15:34 UTC, vshakirova commented on src-java/network-topology/network-storm-topology/src/main/java/org/openkilda/wfm/topology/network/controller/sw/PhysicalPort.java
> +    private long currSpeed;
oki, will fix that)

2022-05-27 05:02 UTC, vshakirova commented on src-java/network-topology/network-storm-topology/src/main/java/org/openkilda/wfm/topology/network/controller/sw/SwitchFsm.java
> +        portUpdate(makePortRecord(Endpoint.of(switchId, context.getPortNumber()), context.getPortMaxSpeed(),
fixed

2022-05-30 15:48 UTC, vshakirova commented on src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/frames/PortFrame.java
> +    public static final String OWNS_BY_PORT = "owns";
Lets try this)

2022-05-30 15:49 UTC, vshakirova commented on src-java/network-topology/network-storm-topology/src/main/java/org/openkilda/wfm/topology/network/controller/port/PortFsm.java
> +    private void createOrUpdate(PortFsmState from, PortFsmState to, PortFsmEvent event, PortFsmContext context) {
Will move it, thank you

2022-06-02 07:50 UTC, vshakirova commented on src-java/network-topology/network-storm-topology/src/main/java/org/openkilda/wfm/topology/network/controller/port/PortFsm.java
> -        PortFsmFactory(PersistenceManager persistenceManager) {
thanks, moved it

2022-06-02 07:51 UTC, vshakirova commented on src-java/network-topology/network-storm-topology/src/main/java/org/openkilda/wfm/topology/network/controller/port/PortFsm.java
> +            port.setMaxSpeed(portData.getMaxSpeed());
I'll place a simple null check and leave a TODO comment

2022-06-02 14:18 UTC, niksv approved these changes

2022-06-02 14:18 UTC, niksv commented on src-java/base-topology/base-storm-topology/src/test/java/org/openkilda/wfm/share/mappers/PortMapperTest.java
> +                10000000L, PortChangeType.UP);
cur speed and max speed still equal

2022-06-02 15:04 UTC, surabujin approved these changes

2022-06-03 14:30 UTC, surabujin approved these changes
LGTM

2022-06-06 12:21 UTC, dpoltavets approved these changes

2022-06-10 06:51 UTC, merged