Update rule manager docs
telstra/open-kilda pull request #4830
Opened 2022-05-31 14:06 UTC by rozdy

Add install isl service rules sequence diagram

2022-06-06 14:36 UTC, surabujin requested changes

2022-06-08 12:56 UTC, rozdy commented on docs/design/rule-manager/isl-service-rules.puml
> +participant IslHandler
Renamed.

2022-06-08 13:08 UTC, surabujin approved these changes

2022-06-13 09:35 UTC, nikitamarchenko approved these changes

2022-06-13 09:35 UTC, nikitamarchenko commented on docs/design/rule-manager/isl-service-rules.puml
> +participant NetworkIslService
Add "box "XXX Topology" #LightBlue" for show borders of topology \ service etc.

2022-06-17 06:53 UTC, merged