Added possibility to delete lagPort in case no lagPort on a switch
telstra/open-kilda pull request #4866
Opened 2022-07-05 06:56 UTC by Nexgen90

Added error type check for prevent the FSM fail If lag port is exists in database but has already deleted in switch;

Related to #4729

2022-07-05 07:26 UTC, dpoltavets requested changes

2022-07-06 08:48 UTC, Nexgen90 commented on src-java/swmanager-topology/swmanager-storm-topology/src/main/java/org/openkilda/wfm/topology/switchmanager/service/DeleteLagPortService.java
> +            log.warn("Port is stored in a database but doesn't exist in a switch");
Fixed

2022-07-06 09:02 UTC, dpoltavets approved these changes

2022-07-06 10:52 UTC, niksv approved these changes

2022-07-06 16:10 UTC, vshakirova approved these changes

2022-07-19 07:48 UTC, artHalMirantis commented
Verified on the virtual environment
test  - Passed

2022-07-21 14:24 UTC, merged