Reworked FL RuleManager response topic handling
telstra/open-kilda pull request #4870
Opened 2022-07-05 19:23 UTC by nrydanov

2022-07-08 08:55 UTC, nrydanov commented on src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/KafkaChannel.java
> +    public String getSpeakerFlowHsTopic() {
Thanks

2022-07-08 08:55 UTC, nrydanov commented on src-java/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/api/request/rulemanager/BaseSpeakerCommandsRequest.java
> +    protected String sender;
Agree with you

2022-07-08 09:03 UTC, dpoltavets requested changes

2022-07-08 09:03 UTC, dpoltavets commented on src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/rulemanager/OfBatchExecutor.java
> +    private final String sender;
It's better to name it something like `incomeTopic` or `sourceTopic`. Be more accurate with naming.

2022-07-08 12:07 UTC, dpoltavets approved these changes

2022-07-11 09:12 UTC, niksv approved these changes

2022-07-12 16:26 UTC, vkhalin approved these changes

2022-07-21 14:32 UTC, merged