Handling RequestRejectedException and proper logging of correlation_id
telstra/open-kilda pull request #4886
Opened 2022-07-20 17:43 UTC by sergii-iakovenko

Resolves #4305

2023-04-05 06:47 UTC, pablomuri requested changes

2023-04-05 06:47 UTC, pablomuri commented on src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/utils/RequestRejectedExceptionFilter.java
> +/* Copyright 2022 Telstra Open Source
Please, update the year

2023-04-12 20:33 UTC, durgakako commented on src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/utils/RequestRejectedExceptionFilter.java
> +/* Copyright 2022 Telstra Open Source
updated to 2023.

2023-04-13 06:08 UTC, niksv approved these changes

2023-04-17 13:01 UTC, pablomuri approved these changes

2023-04-25 08:40 UTC, merged