Able to write stats data in multiple OpenTSDB dabases
telstra/open-kilda pull request #4940
Opened 2022-08-30 18:52 UTC by surabujin

Create separate "channel" of stats datapoint processing for each defined
into config file OpenTSDB target/host.
    
Each "channel" have own kafka spout (with own group-id), so in case of
errors and "tuple repeats" done by storm everything will work correct.

Part of #4925

2022-09-01 15:00 UTC, surabujin commented on confd/vars/docker-compose.yaml
> +no_gui: true
Yes.

2022-09-07 06:54 UTC, niksv approved these changes
Pr has wrong description (with new internal kafka topic)

2023-03-06 16:38 UTC, pablomuri commented
The last change just rebases the branch with develop.

2023-03-07 12:00 UTC, dmitrii-beliakov commented on src-java/opentsdb-topology/opentsdb-storm-topology/src/main/java/org/openkilda/wfm/topology/opentsdb/OpenTsdbTopology.java
> +                        "Target name is empty string (property: \"%s\", prefix: \"%s\")", property, prefix));
The target's name is an empty string

2023-03-07 16:43 UTC, pablomuri commented on src-java/opentsdb-topology/opentsdb-storm-topology/src/main/java/org/openkilda/wfm/topology/opentsdb/OpenTsdbTopology.java
> +        List<String> enableDisableBolts = new ArrayList<>();
Actually, there are not disabled. I've change the name

2023-03-07 16:43 UTC, pablomuri commented on src-java/opentsdb-topology/opentsdb-storm-topology/src/main/java/org/openkilda/wfm/topology/opentsdb/OpenTsdbTopology.java
> +                        "Target name is empty string (property: \"%s\", prefix: \"%s\")", property, prefix));
done

2023-03-07 16:43 UTC, pablomuri commented on src-java/opentsdb-topology/opentsdb-storm-topology/src/main/java/org/openkilda/wfm/topology/opentsdb/OpenTsdbTopology.java
> +            if (value == null || value.isEmpty()) {
done

2023-03-07 16:43 UTC, pablomuri commented on src-java/opentsdb-topology/opentsdb-storm-topology/src/main/java/org/openkilda/wfm/topology/opentsdb/OpenTsdbTopology.java
> +            targets.put(name, (String) entry.getValue());
done

2023-03-08 12:15 UTC, dmitrii-beliakov approved these changes

2023-03-09 05:53 UTC, niksv commented on confd/vars/main.yaml
> +kilda_victoriametrics_port: "4242"
Opentdstb and victoria have equal port 4242. As we can run both DBs for local env will we have problems with "Address 127.0.0.1:4242 is already in use"?

2023-05-25 20:00 UTC, dmitrii-beliakov approved these changes

2023-06-07 17:27 UTC, dmitrii-beliakov approved these changes

2023-06-15 10:39 UTC, pablomuri requested changes
Add an explanation about the differences between the victoria metrics and opentsdb API to read

2023-07-11 12:07 UTC, pablomuri approved these changes

2023-07-14 13:55 UTC, merged