HA flows Part 16: Add auto reroute
telstra/open-kilda pull request #5225
Opened 2023-05-30 16:31 UTC by niksv

Related to #5061
Closes #5238

2023-06-05 11:48 UTC, artHalMirantis approved these changes
can be released with the current test scope

tasks to do:
https://github.com/telstra/open-kilda/issues/5231

2023-06-05 16:05 UTC, pablomuri requested changes

2023-06-06 05:08 UTC, Fedichk approved these changes

2023-06-06 05:08 UTC, Fedichk commented on src-java/kilda-model/src/main/java/org/openkilda/model/HaFlow.java
> +     * Recalculates and set statuses of HA-sub fLows based on paths statuses.
fLows -> flows

2023-06-06 10:23 UTC, niksv commented on src-java/flowhs-topology/flowhs-messaging/src/main/java/org/openkilda/messaging/command/BaseRerouteRequest.java
> +@Data()
looks like no

2023-06-06 10:23 UTC, niksv commented on src-java/flowhs-topology/flowhs-messaging/src/main/java/org/openkilda/messaging/command/yflow/YFlowRerouteRequest.java
> +        this(flowId, new HashSet<>(), reason, false);
Don't know. Replaced back

2023-06-06 10:23 UTC, niksv commented on src-java/flowhs-topology/flowhs-messaging/src/test/java/org/openkilda/messaging/SerializationTest.java
> +/* Copyright 2020 Telstra Open Source
done

2023-06-06 10:23 UTC, niksv commented on src-java/flowhs-topology/flowhs-messaging/src/test/java/org/openkilda/messaging/SerializationTest.java
> +    }
done

2023-06-06 10:23 UTC, niksv commented on src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/create/actions/ResourcesAllocationAction.java
> +                haFlow.getHaSubFlows().forEach(subFlow -> subFlow.setStatus(FlowStatus.IN_PROGRESS));
There are many cases when statuses may be different:
1. one subflow is broken:
 sub1: `down`
 sub2: `up`
 HA-flow `down`

2. one subflow is degraded
   sub1: `defraded`
   sub2: `up`
   HA-flow: `degraded`

2023-06-06 10:23 UTC, niksv commented on src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/delete/actions/ValidateHaFlowAction.java
> +            haFlow.getHaSubFlows().forEach(subFlow -> subFlow.setStatus(FlowStatus.IN_PROGRESS));
same

2023-06-06 10:23 UTC, niksv commented on src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/pathswap/actions/HaFlowValidateAction.java
> +            haFlow.getHaSubFlows().forEach(subFlow -> subFlow.setStatus(FlowStatus.IN_PROGRESS));
same

2023-06-06 10:23 UTC, niksv commented on src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/pathswap/actions/RecalculateFlowStatusAction.java
>                  haFlow.setStatus(status);
what case? we are updating Subflow statuses in the next line

2023-06-06 10:23 UTC, niksv commented on src-java/kilda-model/src/main/java/org/openkilda/model/FlowPath.java
> +        return null;
I think `if` is more readable in this case

2023-06-06 10:23 UTC, niksv commented on src-java/kilda-model/src/main/java/org/openkilda/model/HaFlow.java
> +        return subPaths;
done

2023-06-06 10:23 UTC, niksv commented on src-java/kilda-model/src/main/java/org/openkilda/model/HaFlow.java
> +     * Recalculates and set statuses of HA-sub fLows based on paths statuses.
good catch. fixed

2023-06-06 10:35 UTC, pablomuri commented on src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/create/actions/ResourcesAllocationAction.java
> +                haFlow.getHaSubFlows().forEach(subFlow -> subFlow.setStatus(FlowStatus.IN_PROGRESS));
ok, then it is ok

2023-06-06 10:37 UTC, pablomuri commented on src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/pathswap/actions/RecalculateFlowStatusAction.java
>                  haFlow.setStatus(status);
yes, you're right

2023-07-14 13:55 UTC, merged