open-kilda-5242 Migrate all unit tests from JUnit4 to JUnit5 v4
telstra/open-kilda pull request #5286
Opened 2023-07-11 13:13 UTC by IvanChupin

This PR contains the Junit4->Junit5 migration for the following modules:

testing
reroute-topology
rule-manager

closes #5242

2023-07-13 14:38 UTC, pablomuri approved these changes

2023-07-17 13:20 UTC, dmitrii-beliakov commented on src-java/rule-manager/rule-manager-implementation/src/test/java/org/openkilda/rulemanager/utils/RuleManagerHelperTest.java
> +        FlowSpeakerData command1 = buildFullFlowSpeakerCommandData(METER_ID_1,  null);
extra space

2023-07-17 13:21 UTC, dmitrii-beliakov requested changes
please fix the typos, otherwise looks good!

2023-07-18 09:48 UTC, dmitrii-beliakov approved these changes

2023-08-08 08:12 UTC, merged