5345: [TEST] Skip reset lab env if required
telstra/open-kilda pull request #5354
Opened 2023-08-28 12:29 UTC by yuliiamir

2023-08-28 12:58 UTC, artHalMirantis commented
why do we need such toggle?

2023-08-28 13:04 UTC, pkazlenka requested changes

2023-08-28 13:04 UTC, pkazlenka commented on src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/env/EnvExtension.groovy
> +    @Value('${reset.lab_state}')
Let's make sure that we behave as before this change by default. Add default value 'true' here:
```
@Value('${reset.lab_state:true}')

2023-08-28 13:04 UTC, pkazlenka commented on src-java/testing/functional-tests/kilda.properties.example
> +reset.lab_state=true
Original issue suggested skipping healthcheck as well. Please, implement.

2023-08-28 13:04 UTC, yuliiamir commented
By using this option we can avoid resetting the topology state and decrease time of the test execution.

2023-08-28 14:23 UTC, yuliiamir commented on src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/HealthCheckSpecification.groovy
> +                 allZookeeperNodesInExpectedState].eachParallel { it() }
Decided to keep these two basic checks to avoid unnecessary failure investigation.

2023-08-28 14:25 UTC, yuliiamir commented on src-java/testing/functional-tests/kilda.properties.example
> +reset.lab_state=true
Done.

2023-08-28 14:40 UTC, artHalMirantis approved these changes

2023-08-29 14:18 UTC, pkazlenka approved these changes

2023-09-01 09:14 UTC, yuliiamir commented on src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/env/EnvExtension.groovy
> +            isTopologyRebuildRequired ? buildVirtualEnvironment() : topology.setLabId(labService.getLabs().first().labId)
added labId set up as it is required for some switch-related tests

2023-09-05 14:08 UTC, merged