[TEST]: 5208: Server42 RTT: HaFlow
telstra/open-kilda pull request #5481
Opened 2023-11-21 17:22 UTC by yuliiamir

2024-01-30 11:02 UTC, pkazlenka requested changes
Good, but some minor problems should be solved.

2024-01-30 11:02 UTC, pkazlenka commented on src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/server42/Server42HaFlowRttSpec.groovy
> +        }
Amount of TSDB calls can be reduced twice here as well.

2024-01-30 18:36 UTC, yuliiamir commented on src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
> +    static void verifyAbsenceOfServer42FlowRttRules(def initialSwitchRtt) {
Done

2024-01-30 18:36 UTC, yuliiamir commented on src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
> +            assert requiredState ? (s42Rules.size() == amountOfS42Rules) : s42Rules.empty
Updated

2024-01-30 18:37 UTC, yuliiamir commented on src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
> +    static def changeFlowRttSwitch(Switch sw, boolean requiredState) {
renamed to setServer42FlowRttForSwitch

2024-01-30 18:37 UTC, yuliiamir commented on src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
> +    static def revertToOriginSwitchSetup(def initialSwitchRtt) {
+

2024-01-30 18:38 UTC, yuliiamir commented on src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/server42/Server42FlowRttSpec.groovy
> +        sleep(3000)
the appropriate method has been added (check all switches with server42 support)

2024-01-30 18:39 UTC, yuliiamir commented on src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/server42/Server42HaFlowRttSpec.groovy
> +            assert northbound.validateSwitch(swT.shared.dpId).rules.missing.sort() == cookiesToDelete.sort()
will update after the new logic for switch validation/sync

2024-01-31 10:11 UTC, pkazlenka commented on src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
> +    static List<FlowEntry> s42SwitchRules(SwitchId swId) {
What if we have methods `getServer42SwitchRules()` and `getExpectedServer42SwitchRules()` (this one would calculate expected rules based on switch properties) and compare them in tests?

2024-04-18 10:24 UTC, yuliiamir commented on src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/server42/Server42FlowRttSpec.groovy
> +        flow && flowHelperV2.deleteFlow(flow.flowId) && switchHelper.verifyAbsenceOfServer42FlowRttRules(initialSwitchProps.keySet())
Due to the specificity of the test(verifyAbsenceOfServer42FlowRttRules), flow deletion should be executed as a first step of the cleanup section.

2024-04-19 11:39 UTC, pablomuri approved these changes

2024-04-19 11:50 UTC, merged