[TEST]: Y-Flow: Refactoring: Update operation
telstra/open-kilda pull request #5616
Opened 2024-03-19 17:26 UTC by yuliiamir

2024-03-20 09:49 UTC, pkazlenka requested changes

2024-03-20 16:26 UTC, yuliiamir commented on src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/model/YFlowExtended.groovy
> +    YFlowExtended sendPartialUpdateRequest(YFlowPatchPayload updateRequest) {
I was thinking about update() as a completed operation when an object is in the desired state.
As for the sending update/partial update request, it is the initial stage of the operation without confirmation of successful operation execution.

2024-03-20 16:31 UTC, yuliiamir commented on src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/CustomEntityMatcher.groovy
> +        Gson gson = gson(typesToIgnore, patternsToIgnore, circularReferenceTypes)
A new approach has been used to compare actual and expected YFlowExtended entities.

2024-03-22 09:55 UTC, pkazlenka commented on src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/model/YFlowExtended.groovy
> +    void hasTheSamePropertiesAsExpected(YFlowExtended expectedYFlowExtended, boolean isYPointVerificationIncluded = true) {
I'd rename to 'hasTheSamePropertiesAs()`, so it could be read as an english sentence in use: 
`yFlow1.hasTheSamePropertiesAs(yFlow2)`

2024-03-22 09:57 UTC, pkazlenka approved these changes

2024-03-22 11:50 UTC, pkazlenka approved these changes

2024-03-27 11:45 UTC, merged